### ISSUE TITLE
Add retry option to settings file when the request fails by requests attempts limit

### ISSUE THREAD

**Issue by heliomar-pena** [victor-heliomar/i18n-populator#6]
Create a retry option on settings file when the request fails by request attempts limit, so user can select if he want stop or continue, how many times wants to continue and how many time should be delayed the next attempt

**Comment by victor-heliomar** [comment]
Sadly seems like Google blocks you by IP and don't let you continue even hours after you've been blocked. Tried to fix it using proxies but don't worked on my side. Seems like the only solution by the moment is to use a VPN when your IP was blocked (if you are thinking on doing various translateds at the same). 

I will work on "save requests" allowing translating various texts on a same request. So free limit will be 100% used.

I would also explore leave more time between each translation only to see if that increment the quantity of calls that you can do before of be blocked.

**Comment by victor-heliomar** [comment]
Another approach:

Use multiple free APIs to retry when max attempt error was reached in one of them, I found this: https://github.com/plainheart/bing-translate-api

**Comment by victor-heliomar** [comment]
Retry option is not possible due we the request limit error of Google is persistent almost by 1 hour, not sure if more. But nobody would wait that time to get the translate. I'd suggest continue this issue as a "Change of Translate engine when request limit was reached"

> Another approach:
> 
> Use multiple free APIs to retry when max attempt error was reached in one of them, I found this: https://github.com/plainheart/bing-translate-api

**Comment by victor-heliomar** [comment]
Now when a request fail it continues with the next engine selected on the configuration file or some of the default engines preselected. So retry option is now a true! Issue solved
